language: java
script:
  - mkdir bin
  - javac -d bin -cp lib/junit-4.12.jar src/me/cyandev/*.java src/me/cyandev/test/*.java
  - java -cp lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar:bin org.junit.runner.JUnitCore me.cyandev.test.AlgorithmsTestSuite
