language: java
script:
  - mkdir bin
  - javac -d bin -cp lib/junit-4.12.jar `find src -type f -name '*.java' | paste -s -d ' ' -`
  - java -cp `find lib -type f | paste -s -d ':' -`:bin org.junit.runner.JUnitCore me.cyandev.test.AlgorithmsTestSuite
